### ISSUE TITLE
Data not populating

### ISSUE THREAD

**Issue by mrknify** [Fumlop/EliteMeritTracker#6]
![image](https://github.com/user-attachments/assets/90fd8270-fad0-4158-8c7f-7a718c596264)
![image](https://github.com/user-attachments/assets/736a2a78-fce1-4fe5-8d0d-b2dd6af9084c)
Data not populating, rebooted EDMC, and game.

**Comment by Fumlop** [comment]
What u mean with populate... The field is mainly to add manually merits.

Normally when u swap systems the tool checks the system an u can add manually earned merits, the ok button is misleading and will be renamed to "add"

Journal logs just contains one time merits, if the game is loaded. Afterwards u needs to manually add merits for the current sys.

But I will check.

**Comment by mrknify** [comment]
![image](https://github.com/user-attachments/assets/e6d1aa2d-d504-4e5b-a401-8f8da65581a6)
![image](https://github.com/user-attachments/assets/8cdca1d3-02a9-4037-b41b-a2df6202b536)
![image](https://github.com/user-attachments/assets/74f4f126-f85d-4df5-a563-5e8187e94c6d)

**Comment by Fumlop** [comment]
Ah I think I know what's wrong, take 0.1.0 as long as this problem exists.

**Comment by mrknify** [comment]
I tried with 0.1.0 it didn't fill the values.

Am I supposed to leave current system to see the merit value populate?

**Comment by Fumlop** [comment]
The overall merits should be shown like this in 0.1.0

![2024-11-24_22_39_10-E_D_Market_Connector](https://github.com/user-attachments/assets/999677b0-de24-4cfc-a926-08fff4e9ec7a)

Current and last needs to be updated manually in 0.2.x when I fix the bug.

There is no possibility to update from journal fdev didn't give us that currently. There is a single event for all merits in the game.

When fdev is fixing it, the tool will automatically count merits but for now I implement a manual way.

**Comment by Fumlop** [comment]
New version available.. Reminder.. Tracking merits is currently only manually possible.

**Comment by Fumlop** [comment]
I keep this issue stale until fdev gives us some love.
